import {
    DocumentText24Regular,
    DataBarVertical24Regular,
    Mic24Regular,
    VideoClip24Regular,
    Image24Regular,
    VideoClipMultiple24Regular,
} from "@fluentui/react-icons";


export const services = [
    {
        id: 1,
        title: "AI Website Generator",
        description: '"Viverra viverra nibh enim et aliquam, enim.',
        icon: DocumentText24Regular,
        badge: "New",
        badgeColor: "orange",
        gradient: "linear-gradient(135deg, #fff7ed, #fef3c7)",
        iconBg: "#ffedd5",
        iconColor: "#f97316",
        borderColor: "#fdba74",
    },
    {
        id: 2,
        title: "AI Business Strategy Generator",
        description: '"Viverra viverra nibh enim et aliquam, enim.',
        icon: DataBarVertical24Regular,
        badge: "New",
        badgeColor: "blue",
        gradient: "linear-gradient(135deg, #eff6ff, #e0e7ff)",
        iconBg: "#dbeafe",
        iconColor: "#2563eb",
        borderColor: "#93c5fd",
    },
    {
        id: 3,
        title: "AI Speech Generator",
        description: '"Viverra viverra nibh enim et aliquam, enim.',
        icon: Mic24Regular,
        badge: "New",
        badgeColor: "orange",
        gradient: "linear-gradient(135deg, #fff7ed, #fef3c7)",
        iconBg: "#ffedd5",
        iconColor: "#f97316",
        borderColor: "#fdba74",
    },
    {
        id: 4,
        title: "AI Video Generator",
        description: '"Viverra viverra nibh enim et aliquam, enim.',
        icon: VideoClip24Regular,
        badge: "New",
        badgeColor: "blue",
        gradient: "linear-gradient(135deg, #eff6ff, #e0e7ff)",
        iconBg: "#dbeafe",
        iconColor: "#2563eb",
        borderColor: "#93c5fd",
    },
    {
        id: 5,
        title: "AI Image Generator",
        description: '"Viverra viverra nibh enim et aliquam, enim.',
        icon: Image24Regular,
        badge: "New",
        badgeColor: "orange",
        gradient: "linear-gradient(135deg, #fff7ed, #fef3c7)",
        iconBg: "#ffedd5",
        iconColor: "#f97316",
        borderColor: "#fdba74",
    },
    {
        id: 6,
        title: "AI Video Editor",
        description: '"Viverra viverra nibh enim et aliquam, enim.',
        icon: VideoClipMultiple24Regular,
        badge: "New",
        badgeColor: "blue",
        gradient: "linear-gradient(135deg, #eff6ff, #e0e7ff)",
        iconBg: "#dbeafe",
        iconColor: "#2563eb",
        borderColor: "#93c5fd",
    },
];